import Head from 'next/head'
import { Layout, Intro, Data, Info, Categories, Services, Partners, Contact, Footer } from '@components/index'
// import Image from 'next/image'

//importar los componentes
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const location = { pathName: "home" }

  return (
    <>
      <Head>
        <title>FerreDiamante</title>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Layout location={location}>
        <Intro/>
        <Data/>
        <Info/>
        <Categories/>
        <Services/>
        <Partners/>
        <Contact/>
        <Footer/>
      </Layout>
    </>
  )
}
